[package]
name = "termod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "termod"

[[bin]]
name = "widget_vec"

[dependencies]
crossterm = "0.27.0"
rand = "0.8.5"
